<?php

namespace App\Enums;

final class MediaLinks
{
    const TrailerKeys = [
        '0hgHY9k-44U',
        'BcDK7lkzzsU',
        'go6GEIrcvFY',
        'WR7cc5t7tv8',
        'd9MyW72ELq0',
        'RlOB3UALvrQ',
        'giXco2jaZ_4',
        '8lIR-ONH6KY',
        'kpGo2_d3oYE',
        'Too3qgNaYBE',
        'G9oRlcTQe5A',
        'qEVUtrk8_B4',
        'X0tOpBuYasI',
        'HyEOrBtb4_g',
        'oQMc7Sq36mI',
        'Olp0-7aQJNo',
        'smTK_AeAPHs',
        'BRb4U99OU80',
        'h74AXqw4Opc',
        'CegntUX8kRE',
        '7v75fm0c7ak',
        'CQDXtD2HJAs',
        'PXGeDSzy8mQ',
        'BH-BxB8E0cc',
        '2QKg5SZ_35I'
    ];

    const ImageLinks = ['https://lumiere-a.akamaihd.net/v1/images/p_luca_21670_3c13c611.jpeg',
        'https://dx35vtwkllhj9.cloudfront.net/paramountpictures/smile/images/regions/us/onesheet.jpg',
        'https://dvvy6louqcr7j.cloudfront.net/vista/HO00013811/heroPoster/Shazam-Fury-of-the-Gods.png',
        'https://cdn.tuftsdaily.com/2018/04/a-quiet-place.jpg',
        'https://amc-theatres-res.cloudinary.com/v1667397461/amc-cdn/production/2/movies/53700/53699/PosterDynamic/145397.jpg',
        'https://images.fandango.com/ImageRenderer/0/0/redesign/static/img/default_poster.png/0/images/masterrepository/Fandango/226753/BlackPanther-WakandaForever_Payoff_1-Sht_v10_lg.jpg',
        'https://images.fandango.com/ImageRenderer/0/0/redesign/static/img/default_poster.png/0/images/masterrepository/Fandango/219625/tgmdomonlinedigitalkeyartt-cruisestandingjetv10.jpg',
        'https://www.gscmovies.com.my/wp-content/uploads/2022/10/Catch-it-from-5-May-2020-onwards-on-Astro-Best-50.jpg',
        'https://books.disney.com/content/uploads/2023/01/1368077226-240-scaled.jpg',
        'https://m.media-amazon.com/images/M/MV5BOGZmYzVkMmItM2NiOS00MDI3LWI4ZWQtMTg0YWZkODRkMmViXkEyXkFqcGdeQXVyODY0NzcxNw@@._V1_.jpg',
        'https://m.media-amazon.com/images/M/MV5BY2NkZTEyYTgtMjcxYy00MzE4LTkxOTQtYzkyZjUxNjc4NTZhXkEyXkFqcGdeQXVyNzQ3NjE1MzI@._V1_.jpg',
        'https://miconcinemas.com/media/2141/john-wick.jpg',
        'https://m.media-amazon.com/images/M/MV5BYzZkOGUwMzMtMTgyNS00YjFlLTg5NzYtZTE3Y2E5YTA5NWIyXkEyXkFqcGdeQXVyMjkwOTAyMDU@._V1_.jpg',
        'https://www.joblo.com/wp-content/uploads/2010/03/2007-spider_man3-3-1.jpg',
        'https://m.media-amazon.com/images/M/MV5BMmY5MDI2YmQtNDM0YS00ZWI3LTlmM2YtYWMzNjYyOWRiZGVhXkEyXkFqcGdeQXVyMTMzODk3NDU0._V1_.jpg',
        'https://m.media-amazon.com/images/W/IMAGERENDERING_521856-T1/images/I/711OskNJSJL.jpg',
        'https://m.media-amazon.com/images/M/MV5BMmZiN2VmMjktZDE5OC00ZWRmLWFlMmEtYWViMTY4NjM3ZmNkXkEyXkFqcGdeQXVyMTI2MTc2ODM3._V1_.jpg',
        'https://m.media-amazon.com/images/M/MV5BMDk4MTdhYzEtODk3OS00ZDBjLWFhNTQtMDI2ODdjNzQzZTA3XkEyXkFqcGdeQXVyMjMxOTE0ODA@._V1_FMjpg_UX1000_.jpg',
        'https://images-wixmp-ed30a86b8c4ca887773594c2.wixmp.com/f/f452aa2c-0c64-4bbf-b065-942b8dbda8bb/dfkmmvn-f68e8366-f189-4a3c-90c5-29862b6edfb3.jpg?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ1cm46YXBwOjdlMGQxODg5ODIyNjQzNzNhNWYwZDQxNWVhMGQyNmUwIiwiaXNzIjoidXJuOmFwcDo3ZTBkMTg4OTgyMjY0MzczYTVmMGQ0MTVlYTBkMjZlMCIsIm9iaiI6W1t7InBhdGgiOiJcL2ZcL2Y0NTJhYTJjLTBjNjQtNGJiZi1iMDY1LTk0MmI4ZGJkYThiYlwvZGZrbW12bi1mNjhlODM2Ni1mMTg5LTRhM2MtOTBjNS0yOTg2MmI2ZWRmYjMuanBnIn1dXSwiYXVkIjpbInVybjpzZXJ2aWNlOmZpbGUuZG93bmxvYWQiXX0.QphXo9ARlXKXmIE2GFItRmr-WgDVM3F0w6qqhgO9P94',
        'https://m.media-amazon.com/images/M/MV5BNmE1YjY2YTgtNmZkNy00NzU1LWI2NTQtNWI3OTBlZmJjMTgxXkEyXkFqcGdeQXVyMTQzNTA5MzYz._V1_FMjpg_UX1000_.jpg',
        'https://m.media-amazon.com/images/M/MV5BMTgwNjU0MDA1Ml5BMl5BanBnXkFtZTgwNzU3NDgwNzE@._V1_.jpg',
        'https://trailers.apple.com/trailers/sony_pictures/love-again/images/poster-large.jpg?lastmod=1',
        'https://encrypted-tbn3.gstatic.com/images?q=tbn:ANd9GcQ3z02k66eMSWvUezGKF9m_1bdSn55NX6eEpJzqR1ZfqPEjOhoz',
        'https://m.media-amazon.com/images/M/MV5BY2E5MzIxNmYtOWY1OC00ZDVmLWIxZDctOWFhZjljOWMzZjcxXkEyXkFqcGdeQXVyNTA3MTU2MjE@._V1_FMjpg_UX1000_.jpg',
        'https://m.media-amazon.com/images/M/MV5BY2NkZTEyYTgtMjcxYy00MzE4LTkxOTQtYzkyZjUxNjc4NTZhXkEyXkFqcGdeQXVyNzQ3NjE1MzI@._V1_.jpg'
    ];

    const Categories = [
        4,
        1,
        3,
        1,
        3,
        3,
        3,
        1,
        4,
        3,
        2,
        3,
        3,
        3,
        3,
        3,
        1,
        1,
        1,
        1,
        1,
        2,
        2,
        2,
        3
    ];

    const Name = [
        'Luca',
        'Smile',
        'Shazam',
        'A quiet place',
        'Avatar',
        'Wakanda Forever',
        'Top Gun: Maverick',
        'THE ONE HUNDRED',
        'The Little Mermaid',
        'Batman Returns',
        'Tangled',
        'John Wick: Chapter 4',
        'Black Adam',
        'THE AMAZING SPIDER-MAN 3',
        'Beast',
        'AQUAMAN 2',
        'EVIL DEAD RISE',
        'Megan',
        'Scream VI',
        'MALUM',
        'I KNOW YOURE IN THERE',
        'LOVE AGAIN',
        'WHATS LOVE GOT TO DO WITH IT',
        'BEAUTIFUL DISASTER',
        'JUMANJI',
    ];
}
